//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Politics
{
    using System;
    using System.Collections.Generic;
    
    public partial class candidates
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public candidates()
        {
            this.candidates_lists = new HashSet<candidates_lists>();
        }
    
        public int id { get; set; }
        public Nullable<int> party { get; set; }
        public string name { get; set; }
        public string info { get; set; }
        public string achievements { get; set; }
        public string election_program { get; set; }
        public string image_src { get; set; }
        public int agent_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<candidates_lists> candidates_lists { get; set; }
        public virtual parties parties { get; set; }
        public virtual users users { get; set; }
    }
}
