//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Politics
{
    using System;
    using System.Collections.Generic;
    
    public partial class comments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public comments()
        {
            this.comments1 = new HashSet<comments>();
        }
    
        public int id { get; set; }
        public int user_id { get; set; }
        public int article_id { get; set; }
        public Nullable<int> parent_comment_id { get; set; }
        public string comment_text { get; set; }
        public System.DateTimeOffset publication_date { get; set; }
        public int rating { get; set; }
    
        public virtual news news { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comments> comments1 { get; set; }
        public virtual comments comments2 { get; set; }
    }
}
