//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Politics
{
    using System;
    using System.Collections.Generic;
    
    public partial class messages
    {
        public int id { get; set; }
        public int sender_id { get; set; }
        public int recepient_id { get; set; }
        public string message_text { get; set; }
        public System.DateTimeOffset sending_time { get; set; }
    
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
    }
}
