//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Politics
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PoliticsDBContext : DbContext
    {
        public PoliticsDBContext()
            : base("name=PoliticsDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<candidates> candidates { get; set; }
        public virtual DbSet<candidates_lists> candidates_lists { get; set; }
        public virtual DbSet<comments> comments { get; set; }
        public virtual DbSet<election_types> election_types { get; set; }
        public virtual DbSet<elections> elections { get; set; }
        public virtual DbSet<messages> messages { get; set; }
        public virtual DbSet<news> news { get; set; }
        public virtual DbSet<parties> parties { get; set; }
        public virtual DbSet<supporters> supporters { get; set; }
        public virtual DbSet<user_roles> user_roles { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<cookies> cookies { get; set; }
    }
}
