//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Politics
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PoliticsDBContext : DbContext
    {
        public PoliticsDBContext()
            : base("name=PoliticsDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Candidate> Candidates { get; set; }
        public virtual DbSet<CandidateOnElection> CandidatesList { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<ElectionType> ElectionTypes { get; set; }
        public virtual DbSet<Election> Elections { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<Article> Articles { get; set; }
        public virtual DbSet<Party> Parties { get; set; }
        public virtual DbSet<Supporter> Supporters { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserCookie> UserCookies { get; set; }
    }
}
