//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Politics
{
    using System;
    using System.Collections.Generic;
    
    public partial class supporters
    {
        public int id { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string image_src { get; set; }
        public int party_id { get; set; }
    
        public virtual parties parties { get; set; }
    }
}
